#define WM_PLAYER WM_USER+101
#define WM_UPDATE_SCREEN WM_USER+102
#define WM_UPDATE_SCREEN_JPEG WM_USER+103
#define WM_UPDATE_SCREEN_BMP24 WM_USER+104
#define WM_SETFRAME_COUNT	WM_USER+105
#define WM_PLAY_STOP WM_USER+106
#define WM_CREATE_CONNECT WM_USER+107